### ISSUE TITLE
[Bug] TypeLoadException

### ISSUE THREAD

**Issue by NgKX1641** [ruudschouten/RoR2-MagneticPickups#2]
TypeLoadException when loading the mod

Log file
[Info   :   BepInEx] TS Manifest: ruudschouten-MagneticPickups-1.1.0
[Info   :   BepInEx] Loading [Magnetic Pickups 1.1.0]
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000019 (from typeref, class/assembly On.RoR2.GravitatePickup, MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
FlashWindow:.cctor()

**Comment by ruudschouten** [comment]
It looks like MMHooks isn't installed, could you check and see if `HookGenPatcher` is present in your mod profile?

**Comment by NgKX1641** [comment]
Yes HookGenPatcher is installed

**Comment by ruudschouten** [comment]
Huh, alright, any other mods? Because I can't reproduce it when I create a new profile with r2modman with just my mod installed

**Comment by NgKX1641** [comment]
Oh god I have lots of mods installed, gimme some time to try and reproduce it

**Comment by NgKX1641** [comment]
Hmm I just tried to create a new profile with the exact same mods installed and everything worked perfectly, so I don't know what went wrong with my previous profile

**Comment by ruudschouten** [comment]
So I guess one of the mods is conflicting with it then, maybe it requires a different version of the HookGenPatcher, but I think that is out of my hands
