### ISSUE TITLE
SotS recompile

### ISSUE THREAD

**Issue by Phreelosu** [ruudschouten/RoR2-MagneticPickups#3]
most mods needed to be recompiled in order to work with Gearbox's wonderful dlc

can you also update this so it works with current game version? 👀

**Comment by yobson1** [comment]
I've been using the mod as normal, I think this is one of the few that doesn't need much if any attention for sots compatibility

**Comment by ruudschouten** [comment]
I haven't gotten the DLC myself yet, but I'll see if the mod works with;out any changes, or do a quick recompile somewhere this weekend

**Comment by ruudschouten** [comment]
I uploaded a new version which worked perfectly for me in the latest version, albeit without the DLC installed, but I don't think that should matter
